### ISSUE TITLE
메인 게시판 레이아웃

### ISSUE THREAD

**Issue by CHAYOUBIN** [kdtkdt/juniorok#5]
메인 게시판 레이아웃

**Comment by limvik** [comment]
유빈님! 아까 디스코드에서 이야기 했던대로, 지금 이슈에서 해야 할 일은 메인 게시판 레이아웃 작성해서 PR 올려주시는 거에요.

지금 작성하신 내용 보니까 메인 게시판 다 만든 이후에 PR 하실 것 같아서 걱정돼서 글 남겨요... ㅋㅋㅋ
